### ISSUE TITLE
Change all reasonable names to `drcog-lulc`

### ISSUE THREAD

**Issue by gadomski** [pholleway/drcog-lulc#10]
There are some names, e.g. entrypoint, that use different naming schemes, e.g. `drcoglulc`. We should change as many as are reasonable to `drcog-lulc` to stick to our naming convention.

The item id of `drcog-hrlulc-pilot` should probably change to `drcog-lulc-hr-pilot`.

**Comment by pholleway** [comment]
Updated drcoglulc to drcog_lulc. 
Updated to item id from drcog-hrlulc-pilot to drcog-lulc-hr-pilot.
